name: Multi-Repository Checkout

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  checkout-and-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: List main repository contents
        run: |
          echo ${{ github.workspace }}
          ls -lR ${{ github.workspace }}
          

