name: Multi-Repository Checkout

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  checkout-and-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Checkout second repository
        uses: actions/checkout@v4
        with:
          repository: mmuyideen/ghaction
          path: gh
     

      - name: List main repository contents
        run: |
          echo ${{ github.workspace }}
          ls -lR ${{ github.workspace }}
          

